---
- name: Add key for repo
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
  tags: install

- name: Add repo for MongoDB
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    filename: mongodb-org-3.2
    state: present
  tags: install

- name: Install packages
  package: name=mongodb-org state=present
  tags: install

- name: Enable and start mongod.service
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
