---
language: python
python:
  - '3.6'
install:
  # - pip install ansible==2.3.0 molecule apache-libcloud testinfra
  - pip install ansible==2.5.1 molecule apache-libcloud testinfra pycrypto
env:
  matrix:
    - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
    - secure: OC/VBnzCsc6PdFs+dAQ2t8C2pzuNBkCIPZkplH2ePXhdtbb+6y86J1q6donA5+0lhv3ZaQ3E9JRqFgjIWTYxJml0/jES6Vr839G0IJI/0Rpw7Az9gtqP01nuI0wl8Y3SElyaZohMpxjFThr1i0L3otTUH1GO8iPKPAPh767qMkkpMhqhC/szH1xhcM/Is9XL5+hZ+WyVFZSaxs/vzDRS2cg6XJSiwtuIrCT5qvwkfDx9yJTshMb1tddrrM6nyyQwLGWtrw0oG30Py19rve+OaDtI84fvv204G9xcWu/RfcE2R5QksvcU7b6jKSjAO7rZmAGQj5VDUAPXaLNw9/z8UrIbj1E8Gq2sShnfSaM7bRgwZM3R0U9wvkOH+uMv9O2F87GXFA6zgUaSGkL7llAeM9HFmXxkUcPem/JekTfQ9JbzYG8GReyMW7bAPxEQZgFeu7pkWmr5wVn1Ir0n5CagIMEKIUdhczlWzjv7WXmFE0gb/a0ADEdJ7dN5ixVpWmq1xE9La/QEURHmHsXHqbqw8rJd/oOvRvd3QiSNjHrJohhlwYhPS1fCOEpPKqi8llvWb9JWgx8KyFRoh4s0M1867lr8RgvLjLg3ol5BcclpCrlxy3LyaEdiDGf5UptqEmBETOqjCoAfF77uvZU7L5hJY3BkxAVYw7EBkPhHX8/N97E=
    - secure: T7v43zGQf7DFU2IXXM1IcEMUdOB+LaVZsa0GhVal3UttzIwuPL73ytasfa1P39otpMU8AHvAsZ44G+KzyNXsGSQjVfcqHPoOknRipDkoODBv3JqKSZtUinInhrZxTFnVRdEcccpd6CQYhcRdOjrE2h8HzCY4GfXD1Ym2qNm3P/Q8Ywgj1RW5n2erVjc2S2rRe2FlsDURp2pe9UhouNHN7QUUSmeOGE8pvk5r2ZKXDykyLd8VoQ2CMt3xSb/r2Uyjwra9jmO7/j6aEpRgjwO1N0ot2FOp8XxFBX/ywWqW3jATVufntHAXaAvKL+FBgGN6molCMxx5jfDH6NLkgW/y7l/kwYhBW8B+oOX2k6NIf1K1wr+1dcdAKjSzgQMdqMwjqR6w10VvaETBXe9p4JXl3Cm/Hz2AZA+5bcvqxMMVyy/JibmBH57jMzMnQXtBvJl2+KmtrpSxRtQVDuyHVATLOsUKTFtzRprY88jb4du99xtwLXr+nbiWEQVWqi4ZWgigpgxTrBxosP+e1jlWQx+gCLTOlzXqoIe2Rn0HdzaL8CxaCBFJqiGzQnDAurk9C81Nrw6xdYDJXuGgKFuKsM4oj5FTW6ILE45p9+uftk+H36lnXPtd4HgDDt2MD+Av0fNO/5Kih3PDq0k6gUzm24xA1HqP4Bt9wd7WO7IW9C09BVw=
    - secure: NU+p/BDzikTr2D5Ng58WJiRIBA6XjgAYghqJqleJQZD6dboGEn0wLYmiuGVkizAE8QHm7eWqLif5YuKlls8jRZUluOwwrTKysQz+C9yv2ZDwH5/FvPtU1SRWN2qmfMaAQCznc+MIYEbVWHxYceeisk2/SjY+olCPJAERjrFvwSfswnqJb/GXyD3wCfihZkPmgiZkUEBtT+xjsJYXYKeWwIE4LnnRhQSZACBe1ARYJORbD6r+MGX9gAJPrf4eKAUCkBKx5zcFcdsS/yBN5DQc0/H2bU+QX6bHfot1F7Jj2NTN8Tq1kQSUOR1pbUW5lmPsW07RHjLQJsCMwejQ6HNIFYx4elTgX5kOGhiSTZ4Lw2FAlf2/+mS1hPEiK6Ovl8GW21L48F6QDqdAhAmDZT/NRvZnTaZ7fWTPhg5Vq8jYY9upnEXg4VXs5foxmPYkE1y9fCzXSvqfJYJdR2bYTi/PfC1BylYXoxvXhiHE2DZjsoyexgi3bMEu+L9DVRtXSK6IXNBvLAJna/+qPc/1JsmKv7BfdMZbDw1kdnQzZsgNIoEvIk7uFtKtl+jZYickD8wf3YKG44psfYaGxdu77QFWZ+Z44RNu3Hw5Wnq+L+aR2PtwRGwoWsa0k53K1J11E9RTx2EWZb+WTgJQivihcs3zN/ygo9bn6mf5wJ282h/xA5c=
script:
  - molecule --debug create
  - molecule converge
  - molecule verify
after_script:
  - molecule destroy
before_install:
  - openssl aes-256-cbc -K $encrypted_03803e8e738b_key -iv $encrypted_03803e8e738b_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mv google_compute_engine /home/travis/.ssh/
  - chmod 0600 /home/travis/.ssh/google_compute_engine
  
