---

# set -e
# # install Mongo-DB

# # add key
# apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927

# # add repo
# echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" > /etc/apt/sources.list.d/mongodb-org-3.2.list

# # update info about repo 
# apt update

# # install package
# apt install -y mongodb-org

# # enable and start mongodb
# systemctl enable mongod
# systemctl start mongod

- name: Install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Add key for repo
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927

    - name: Add repo for MongoDB
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        filename: mongodb-org-3.2
        state: present

    - name: Install packages
      package: name=mongodb-org state=present

    - name: Enable and start mongod.service
      systemd:
        name: mongod
        enabled: yes
        state: started
